version: '2'
services:
    db:
        image: mysql:5.7
        volumes:
          - db_data:/var/lib/mysql
          - ./db_dump:/docker-entrypoint-initdb.d
        restart: always
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    web:
      build: ./web
      links:
        - db:mysql-host
      ports:
        - "80:80"
      restart: always
      depends_on:
        - db

volumes:
  db_data:
    driver: local
